[package]
name = "bls"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
codegen-units = 1
lto = "fat"
debug = true

[dependencies]
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ["std", "unstable"] }
blst = { path = "../../..", features = ["no-threads"] }
# blst = { git = "https://github.com/risc0/blst", tag = "v0.3.14-risczero.2", features = ["no-threads"] }
