[package]
name = "kzg"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
codegen-units = 1
lto = "fat"
debug = true

[dependencies]
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ["std", "unstable"] }
c-kzg = { git = "https://github.com/risc0/c-kzg-4844", tag = "c-kzg/v2.1.0-risczero.1" }

[patch.crates-io]
blst = { path = "../../.." }
# blst = { git = "https://github.com/risc0/blst", tag = "v0.3.14-risczero.2" }